### ISSUE TITLE
DefaultGoSourcePath assumes GOPATH is set

### ISSUE THREAD

**Issue by bketelsen** [uxtoolkit/cog#1]
https://github.com/uxtoolkit/cog/blob/1925fd148fa51c11328b0c6d4667f7bdbca3c516/cog.go#L26

GOPATH is not required to be set since [this change](https://github.com/golang/go/issues/17262)
If the default GOPATH is used without setting GOPATH manually, this code fails.  It would be better to check to see if GOPATH is set, if not, use `build.Default.GOPATH` from the `go/build` package.

**Comment by EngineerKamesh** [comment]
Thank you for the PR that resolved this issue.
