### ISSUE TITLE
Paths not Windows friendly

### ISSUE THREAD

**Issue by bketelsen** [uxtoolkit/cog#3]
Paths throughout the toolkit use unix style slashes and string concatenation.
Change to filepath.Join(first,second) to make these paths windows friendly.

**Comment by EngineerKamesh** [comment]
Thanks for the heads up. Will make the paths more platform agnostic, as per your helpful advice.

**Comment by EngineerKamesh** [comment]
As per your feedback, I have made the pathing platform agnostic.
